name: Build and Test Matrix

on: [push]

jobs:
  pipeline:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: "Release"
        config:
        - {
            name: "Windows 2022 MSVC",
            os: windows-2022,
          }
        - {
            name: "Windows 2019 MSVC",
            os: windows-2019,
          }
        - {
            name: "Ubuntu 20.04",
            os: ubuntu-20.04,
          }
        - {
            name: "macOS Big Sur 11",
            os: macos-11,
          }
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Report CMake version
      run: cmake --version
    - name: Generate build instructions
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake
            -S .
            -B build
            -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()
    - name: Build
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND cmake --build build
          RESULT_VARIABLE result
          OUTPUT_VARIABLE output
          ERROR_VARIABLE output
          ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE
        )
        if (NOT result EQUAL 0)
          string(REGEX MATCH "FAILED:.*$" error_message "${output}")
          string(REPLACE "\n" "%0A" error_message "${error_message}")
          message("::error::${error_message}")
          message(FATAL_ERROR "Build failed")
        endif()


